services:
  evolution_api:
    image: atendai/evolution-api:v1.6.1
    container_name: evolution_gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://localhost:8080
      - DOCKER_ENV=true
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=B6B7C1D8-E9A2-4B3A-8F5E-3D2C1B4A9F0E
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_CLIENT=sqlite
      - DATABASE_CONNECTION_DATABASE=evolution
    volumes:
      - evolution_instances:/evolution/instances

  rdo_app:
    build: .
    container_name: rdo_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - evolution_api

volumes:
  evolution_instances:
